apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    environment: dev
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 24 # Numero de pods
  revisionHistoryLimit: 3 # Numero de revisoes que o deployment vai manter
  selector: # Selector consiste em um conjunto de labels que devem ser iguais aos labels do pod
    matchLabels:
      app: nginx-deployment
      environment: dev
  strategy:
    type: RollingUpdate # Tipo de atualizacao 
    rollingUpdate: # Atualizacao dos pods de forma gradual, um a um para nao impactar o servico
      maxSurge: 1 # Numero de pods a mais que podem ser criados, alem do numero de replicas para acelerar a atualizacao
      maxUnavailable: 1 # Numero de pods que podem ficar indisponiveis durante a atualizacao
  template: # Template do pod que será criado
    metadata: # Labels do pod
      labels:
        app: nginx-deployment
        environment: dev
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.5"
          requests:
            memory: "64Mi"
            cpu: "0.3"
