apiVersion: apps/v1
kind: Deployment # ✅ Mudado para Deployment
metadata:
  name: nginx-server
spec:
  replicas: 3 # ✅ Agora o Kubernetes cria 3 Pods automaticamente
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9113'
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d # ✅ Agora está correto
          subPath: nginx.conf

      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:0.11.0
        args:
        - '-nginx.scrape-uri=http://localhost/metrics'
        resources:
          limits:
            memory: 128Mi
            cpu: 300m # ✅ CPU corrigido
        ports:
        - containerPort: 9113
          name: metrics

      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
          defaultMode: 420
