apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
    environment: dev
  name: nginx-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-deployment
      environment: dev
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-deployment
        environment: dev
    spec:
      containers:
      - image: nginx:1.17.0
        name: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.5"
          requests:
            memory: "64Mi"
            cpu: "0.3"
