apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx-deployment
    dominio: linuxtips
spec:
  selector:
    app: nginx-deployment
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
