apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-role-cert
  namespace: default
spec:
  secretName: platform-role-tls
  duration: 2160h # 90 dias
  renewBefore: 360h # 15 dias antes da expiração
  subject:
    organizations:
    - eks-platform
  commonName: platform-role
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - client auth
  dnsNames:
  - platform-role.example.com
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
