apiVersion: v1
kind: Pod
metadata:
  name: pod-reader-teste
  namespace: default
spec:
  serviceAccountName: pod-reader
  restartPolicy: Always
  containers:
  - name: pod-reader
    image: alpine
    command: [ "sleep", "3600" ]
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "50m"
        memory: "64Mi"
