apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: node-exporter-daemonset
  name: node-exporter-daemonset
spec:
  selector:
    matchLabels:
      app: node-exporter-daemonset
  template: #Template consiste em informações sobre o pod
    metadata:
      labels:
        app: node-exporter-daemonset
    spec:
      hostNetwork: true #Habilita o acesso a rede diretamente do host ou seja o node
      containers:
      - name: node-exporter
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          hostPort: 9100
        volumeMounts: #Volume mounts é um array de objetos que mapeia volumes para o container e nao o volume em si
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys #Monta o diretório /host/sys no container, o /host/sys é um diretório do host
          readOnly: true
      volumes: #Aqui sim é definido o volume
      - name: proc
        hostPath:
          path: /proc
      - name: sys
        hostPath:
          path: /sys

